### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range' what():  stoi

### ISSUE THREAD

**Issue by MagicWinnie** [CHEYSOFF/PACMAN#1]
Вызывается исключение `terminate called after throwing an instance of 'std::out_of_range' what(): stoi` при манипуляции с файлом лидерборда и вводом туда количества очков, превышающих пределы типа данных.

**Comment by MagicWinnie** [comment]
Также ошибка при вводе текста в поле очков

**Comment by CHEYSOFF** [comment]
> Вызывается исключение `terminate called after throwing an instance of 'std::out_of_range' what(): stoi` при манипуляции с файлом лидерборда и вводом туда количества очков, превышающих пределы типа данных.

Если честно, без понятия как можно обойти переполнение того же самого инта или лонг лонга
Единственное что приходит на ум это как-нибудь залочить файл для рядового пользователя, для того чтобы он не мог редактировать лидерборд, еще не знаю как это можно воплотить но идеи есть. Не хочется действовать так радикально, к тому же это скорее всего сложно и вызовет уйму багов.
Если что, я открыт к предложениям :)

**Comment by CHEYSOFF** [comment]
теперь максимальное количество очков которое можно набрать - границы long long
