### ISSUE TITLE
terminate called after throwing an instance of 'std::invalid_argument' what():  stoi

### ISSUE THREAD

**Issue by MagicWinnie** [CHEYSOFF/PACMAN#3]
Если записать никнейм с пробелами, то при следующем запуске вызывается исключение `terminate called after throwing an instance of 'std::invalid_argument' what():  stoi`

**Comment by MagicWinnie** [comment]
Или при удалении количества очков из файла

**Comment by CHEYSOFF** [comment]
Пофиксил в последнем коммите + если есть пробелы в суффиксе, они теперь удаляются
